### ISSUE TITLE
let for functions, def for methods feels inconsistent

### ISSUE THREAD

**Issue by andreyvit** [ckknight/gorillascript#106]
Using `let` for top-level functions and `def` for class methods feels inconsistent. Why not allow `def` for non-method functions too?

**Comment by ckknight** [comment]
Because a `class` can contain arbitrary code, `let` can be used as well as a sort of private static function.

I may add `enum` support later (as an alias for a `const` object) which would also use `def`, so `def` means "add to the current factory/object/whatever we're making".

Also, neither `let` nor `def` need to define a function, any piece of code can be used, e.g. `let x = 5` or `def x = 5`.

**Comment by andreyvit** [comment]
IMO this distinction sucks. It's basically an implementation detail that does not do a good job expressing the intent.

On the other hand, that's why the language has macros, right? Instead of CoffeeScript-style debates I should write a macro that works for me and then come back to show it off. Closing the ticket until then.
